### Get all hikes
GET http://localhost:8085/api/matk


### Insert one hike
POST http://localhost:8085/api/matk
Content-Type: application/json

{
    "nimi": "Suusamatk Jõulumäel",
    "tekst": "Kaunis suusamatk Võrumaa ümbruses.",
    "pilt": "https://example.com/suusamatk-otepaa.jpg"
}


### Delete one hike
DELETE http://localhost:8085/api/matk/6942e217e614d319beaf99c2

### Return participants of one hike
GET http://localhost:8085/api/matk/6942e276934a050309afcbdc/osaleja

### Add on participant to a hike
POST  http://localhost:8085/api/matk/6942e276934a050309afcbdc/osaleja
Content-Type: application/json

{
    "nimi": "Osaleja Nimi 2",
    "email": "osaleja2@email.ee"
}


### Patch data of one hike
PATCH   http://localhost:8085/api/matk/6942e276934a050309afcbdc
Content-Type: application/json

{
    "nimetus": "Kõik korraga",
    "kirjeldus": "muudetud kirjeldus"
}

### Get details of one hike
GET http://localhost:8085/api/matk/6942e276934a050309afcbdc

### Create a new user
POST http://localhost:8085/api/user
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

